# Generated by Django 5.1.4 on 2024-12-07 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='StoreApp.product'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
